name: CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: write                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install
      run: |
        make install
    - name: Format
      run: |
        make format
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Run
      run: |
        make run
    - name: Build
      run: |
        make build
    - name: Upload Optimized Rust Binary as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: optimized-rust-binary
        path: target/release/IDS706_individual_project_2